25 error component
scientist-softserv/webstore pull request #136
Opened 2023-01-19 22:40 UTC by summer-cook

2023-01-20 22:23 UTC, labradford approved these changes

2023-01-21 01:08 UTC, alishaevn requested changes

2023-01-21 01:08 UTC, alishaevn commented on utils/api/helpers.js
> +
can the content of this file be moved to "utils/helpers.js"?

2023-01-23 14:54 UTC, alishaevn requested changes

2023-01-23 14:54 UTC, alishaevn commented on pages/browse/index.js
> +import { configureServices, configureErrors, useFilteredWares } from '../../utils'
alphabetize the imports please.

2023-01-23 14:54 UTC, alishaevn commented on pages/browse/index.js
> +  }
```suggestion
  if (isError) return <Error errors={configureErrors([isError])} router={router} />
```

2023-01-23 14:54 UTC, alishaevn commented on pages/requests/index.js
> +import { dark, useAllRequests, configureErrors } from '../../utils'
alphabetize the imports please.

2023-01-23 14:54 UTC, alishaevn commented on utils/api/configurations.js
> +  if (env == 'development') {
```suggestion
 
   if (env === 'development') {
```

2023-01-23 14:54 UTC, alishaevn commented on utils/api/configurations.js
> +      errorText.push(JSON.stringify(error))
does this behave as you expect it to when the errors array includes an empty hash?

2023-01-23 14:54 UTC, alishaevn commented on utils/api/configurations.js
> +      errorTitle = errors.length > 1 ? 'There were multiple errors.' : error.name
if `errors = [{ title: 'some', message: 'data' }, {}]`, then we only have 1 error and not multiple. this code doesn't account for that scenario as is.

2023-01-23 14:54 UTC, alishaevn commented on utils/api/configurations.js
> +    })
```suggestion
      return { errorText, errorTitle }
    })

```

2023-01-23 14:54 UTC, alishaevn commented on utils/api/configurations.js
> +  if (env == 'production'){
```suggestion

    if (env === 'production') {
```

2023-01-23 14:54 UTC, alishaevn commented on utils/api/configurations.js
> +    }
```suggestion
    }

```

2023-01-23 14:54 UTC, alishaevn commented on pages/requests/index.js
> +  }
can you refactor to a single line?

2023-01-23 14:54 UTC, alishaevn commented on pages/services/[ware].js
> +  }
can you refactor to a single line?

2023-01-23 16:45 UTC, alishaevn approved these changes

2023-01-23 17:41 UTC, merged