156 refactor sending messages
scientist-softserv/webstore pull request #213
Opened 2023-02-16 20:36 UTC by summer-cook

# Story
brings back the ability to send messages, and adds the quotedWareID to the request so it can be passed in the post message request

Ref #156 

# Expected Behavior Before Changes

# Expected Behavior After Changes

# Screenshots / Video

<details>
<summary></summary>

</details>

# Notes

2023-02-16 22:08 UTC, summer-cook commented
@alishaevn I'm going to change this ticket back to a 2, because it look a lot more than just updating the quoted_ware_ids array to use the quotedWareID to bring back all of the message & attachment sending functionality, since it needed to be used when creating requests as well

also, here is the related PR uncommenting everything in the component library: https://github.com/scientist-softserv/webstore-component-library/pull/161/files

2023-02-16 22:15 UTC, summer-cook commented
also, @alishaevn should I change the variable of `quotedWareID` to either `serviceID` or just `wareID` ?

I felt like it might need to be distinguished since there are SO many ids

2023-02-16 23:07 UTC, alishaevn requested changes

2023-02-16 23:07 UTC, alishaevn commented on pages/requests/[id].js
> +          <ActionsGroup initialFiles={files} handleSendingMessagesOrFiles={handleSendingMessagesOrFiles}/>
```suggestion
          <ActionsGroup
            initialFiles={files}
            handleSendingMessagesOrFiles={handleSendingMessagesOrFiles}
          />
```

2023-02-16 23:07 UTC, alishaevn commented on pages/requests/[id].js
> +          <ActionsGroup initialFiles={files} handleSendingMessagesOrFiles={handleSendingMessagesOrFiles}/>
since we know there will be more actions in the future.

2023-02-16 23:07 UTC, alishaevn commented on utils/api/base.js
> +    if (requestID && quotedWareID) {
we're using `posting` for other functions too, and potentially more as the app expands. does the `quotedWareID` _always_ come back in the data object??

2023-02-16 23:07 UTC, alishaevn commented on utils/api/configurations.js
> +      quotedWareID: request.quoted_ware_refs?.[0].id
```suggestion
      quotedWareID: request.quoted_ware_refs?.[0].id,
```

2023-02-16 23:07 UTC, alishaevn commented on utils/api/base.js
> +        quotedWareID
```suggestion
        quotedWareID,
```

2023-02-17 14:25 UTC, alishaevn commented
> also, @alishaevn should I change the variable of `quotedWareID` to either `serviceID` or just `wareID` ?
> 
> I felt like it might need to be distinguished since there are SO many ids

I'd keep it at `quotedWareID` because it is not a ware/service ID. 🙂

2023-02-17 16:05 UTC, alishaevn approved these changes

2023-02-17 16:32 UTC, merged